### ISSUE TITLE
Missing container size

### ISSUE THREAD

**Issue by Gnep** [tardyp/hyper_sh#3]
I'm using the hyper_sh library and it doesn't appear to have a size parameter included which is causing the API to return a "docker.errors.APIError: 400 Client Error: Bad Request ("Illegal container size:")"

**Comment by tardyp** [comment]
Hi,
as per https://docs.hyper.sh/Reference/API/2016-04-04%20[Ver.%201.23]/Container/create.html
The container size must be provided in the label field of container create.
see example
https://github.com/buildbot/buildbot/blob/master/master/buildbot/worker/hyper.py#L157
