### ISSUE TITLE
401 Unauthorized for requests to create container

### ISSUE THREAD

**Issue by frankh** [tardyp/hyper_sh#5]
I can run some things, like client.images() correctly gets the list of images, but trying to call create_container always fails with unauthorized - even though i can run containers with the same keys from the hyper command line

**Comment by tardyp** [comment]
Hi @frankh do you use private repository?
isn't that a duplicate of https://github.com/tardyp/hyper_sh/issues/4 ?

**Comment by frankh** [comment]
No it's not from a private repository - It seems to be unrelated to the pull as the image is already pulled on hyper

**Comment by tardyp** [comment]
@frankh I usually ask the hyper support when such things happen, as they have their server logs, and for security reasons, you usually do not send to much info when doing 40x errors

**Comment by carmark** [comment]
hello @frankh ,

I did try to create a container with `hyper_sh` python library, and it looks like it works well.

How to run it:
* `pip install hyper_sh`
* write a test script, such as:
```
$ cat test.py
from hyper_sh import Client
c = Client("./config.json")  # you can pass a specific config.json
print c.create_container("busybox")
```
* run it and check the result
```
[lei@h8s-single tmp]$ python test.py
{u'Id': u'84d53c0db0164e08d878858252d9181b4d8779884283d217e1c9a6cc76d67724', u'Warnings': None}
[lei@h8s-single tmp]$ hyper ps -a
CONTAINER ID        IMAGE                COMMAND                  CREATED             STATUS                     PORTS                                              NAMES                PUBLIC IP
84d53c0db016        busybox              "sh"                     12 seconds ago      Created                                                                       small-kilby
```

**Comment by frankh** [comment]
@carmark thanks. I'm not sure what's going on. I've tried with 2 different keys from 2 different hyper accounts. Both keys work on the command line (`hyper run --rm busybox`), but both fail using hyper_sh

```
>>> c = Client('~/.hyper/config.json')
>>> c.create_container('busybox')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 170, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 909, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://us-west-1.hyper.sh:443/v1.23/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 135, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 146, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 401 Client Error: Unauthorized ("b'Unauthorized'")
```

**Comment by frankh** [comment]
Ah, I think the problem is it doesn't work on python3

Got it working on my osx machine running python 2.7.12 and inside a docker container running python 2.7.9

It fails inside the same docker container using python 3.6.0. I'm guessing an encoding issue when sending the api request? (unicode instead of bytes?) @tardyp

**Comment by MAliNaqvi** [comment]
@tardyp its the same issue for pulling images, works for python2 but not for python3:

python2:
https://www.dropbox.com/s/2fwrxxrb7fw1rub/Screenshot%202017-03-25%2010.43.46.png?dl=0

python3:
https://www.dropbox.com/s/z1ho38x9popfkt0/Screenshot%202017-03-25%2010.44.12.png?dl=0

**Comment by tardyp** [comment]
@MAliNaqvi you can just copy paste images to github comment box (or better, paster the text!!)
![image](https://cloud.githubusercontent.com/assets/109859/24324243/3ec1cd3c-1183-11e7-8edf-9d5bd4b1307e.png)

**Comment by tardyp** [comment]
I cannot reproduce myself the problem. I am trying to blindly push a fix

**Comment by MAliNaqvi** [comment]
@tardyp with this commit https://github.com/tardyp/hyper_sh/commit/4703a0470989158b867885592b85f503eac0fee0, the pull issue is fixed, 

however the create_container unauthorized error is still present.

**Comment by tardyp** [comment]
Indeed, I can reproduce with create_container

**Comment by tardyp** [comment]
@MAliNaqvi please retry with 1.0.6. The issue should be fixed there

**Comment by MAliNaqvi** [comment]
@tardyp tested. It works! thank you!

**Comment by frankh** [comment]
Yes, it works now, thanks
